=== ultraq/redhorizon/old/projects/(old) Red Horizon XML/Schema/Campaign.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- ========================================== -->
<!-- Red Horizon XSD - Campaign descriptor file -->
<!-- ========================================== -->

<xsd:schema targetNamespace="http://www.ultraq.net.nz/redhorizon/campaign"
	xmlns="http://www.ultraq.net.nz/redhorizon/campaign"
	xmlns:common="http://www.ultraq.net.nz/redhorizon/common"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xsd:import schemaLocation="Common.xsd" namespace="http://www.ultraq.net.nz/redhorizon/common"/>

	<!-- Map schema to custom package -->
	<xsd:annotation>
		<xsd:appinfo>
			<jxb:schemaBindings>
				<jxb:package name="redhorizon.xml.campaign"/>
			</jxb:schemaBindings>
		</xsd:appinfo>
	</xsd:annotation>


	<!-- Root element, campaign info -->
	<xsd:element name="CampaignData">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLCampaignData"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element name="Campaign" type="Campaign"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>


	<!-- Campaign info -->
	<xsd:complexType name="Campaign">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLCampaign"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Name" type="Name"/>
			<xsd:element name="Description" type="Description" minOccurs="0"/>
			<xsd:element name="Mission" type="Mission" maxOccurs="unbounded"/>
			<xsd:element name="Ending" type="Ending" maxOccurs="unbounded"/>
			<xsd:element name="MissionTree" type="MissionTree"/>
		</xsd:sequence>
		<xsd:attribute name="GameType" type="common:GameTypes"/>
	</xsd:complexType>

	<!-- Link Campaign name to translatable text -->
	<xsd:complexType name="Name">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLName"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="common:TranslatableText"/>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- Link Campaign description to translatable text -->
	<xsd:complexType name="Description">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLDescription"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="common:TranslatableText"/>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- Mission info -->
	<xsd:complexType name="Mission">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLMission"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="common:ReferenceableObject"/>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- Mission info link -->
	<xsd:complexType name="MissionRef">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLMissionRef"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="common:ReferencingObject"/>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- Ending info -->
	<xsd:complexType name="Ending">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLEnding"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="common:ReferenceableObject"/>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- Ending info link -->
	<xsd:complexType name="EndingRef">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLEndingRef"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="common:ReferencingObject"/>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- Mission tree structure -->
	<xsd:complexType name="MissionTree">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLMissionTree"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Node" type="MissionNode" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="Root" type="xsd:string" use="required"/>
	</xsd:complexType>

	<!-- Mission tree node -->
	<xsd:complexType name="MissionNode">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLMissionNode"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="common:ReferenceableObject">
				<xsd:sequence>
					<xsd:element name="Mission" type="MissionRef" maxOccurs="unbounded"/>
					<xsd:choice>
						<xsd:element name="WinBranch" type="MissionNodeRef"/>
						<xsd:element name="LoseBranch" type="MissionNodeRef"/>
						<xsd:element name="Ending" type="EndingRef"/>
					</xsd:choice>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- Mission tree node link -->
	<xsd:complexType name="MissionNodeRef">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLMissionNodeRef"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="common:ReferencingObject"/>
		</xsd:complexContent>
	</xsd:complexType>

</xsd:schema>

=== ultraq/redhorizon/old/configs/_Red Alert/XML/Campaign.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- ==================================== -->
<!-- Red Horizon - Red Alert mission tree -->
<!-- ==================================== -->

<campaign:CampaignData xmlns="http://www.westwood.com/redalert"
	xmlns:campaign="http://www.ultraq.net.nz/redhorizon/campaign"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ultraq.net.nz/redhorizon/campaign ../../Schema/Campaign.xsd">

	<!-- Red Alert: Allied campaign -->
	<campaign:Campaign GameType="RED_ALERT">
		<campaign:Name Text="CAMPAIGN_RA_ALLIES"/>
		<campaign:Description Text="DESCRIPTION_RA_ALLIES"/>

		<campaign:Mission ID="Scg01ea"/>

		<campaign:Ending ID="Win_Allies"/>
		<campaign:Ending ID="Lose_Allies"/>

		<campaign:MissionTree Root="Scg01">
			<campaign:Node ID="Scg01">
				<campaign:Mission Ref="Scg01ea"/>
				<campaign:Ending Ref="Win_Allies"/>
			</campaign:Node>
		</campaign:MissionTree>
	</campaign:Campaign>

	<!-- Red Alert: Soviet Campaign -->
	<campaign:Campaign GameType="RED_ALERT">
		<campaign:Name Text="CAMPAIGN_RA_SOVIET"/>
		<campaign:Description Text="DESCRIPTION_RA_SOVIET"/>

		<campaign:Mission ID="Scu01ea"/>

		<campaign:Ending ID="Win_Soviet"/>
		<campaign:Ending ID="Lose_Soviet"/>

		<campaign:MissionTree Root="Scu01">
			<campaign:Node ID="Scu01">
				<campaign:Mission Ref="Scu01ea"/>
				<campaign:Ending Ref="Win_Soviet"/>
			</campaign:Node>
		</campaign:MissionTree>
	</campaign:Campaign>

</campaign:CampaignData>
