=== ultraq/redhorizon/old/projects/(old) Red Horizon XML/Schema/Warheads.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- ================================ -->
<!-- Red Horizon XSD - Warhead schema -->
<!-- ================================ -->

<xsd:schema targetNamespace="http://www.ultraq.net.nz/redhorizon/warheads"
	xmlns="http://www.ultraq.net.nz/redhorizon/warheads"
	xmlns:common="http://www.ultraq.net.nz/redhorizon/common"
	xmlns:media="http://www.ultraq.net.nz/redhorizon/media"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xsd:import schemaLocation="Common.xsd" namespace="http://www.ultraq.net.nz/redhorizon/common"/>
	<xsd:import schemaLocation="Media.xsd" namespace="http://www.ultraq.net.nz/redhorizon/media"/>

	<!-- Map schema to custom package -->
	<xsd:annotation>
		<xsd:appinfo>
			<jxb:schemaBindings>
				<jxb:package name="redhorizon.xml.warheads"/>
			</jxb:schemaBindings>
		</xsd:appinfo>
	</xsd:annotation>

	<!-- Root element, warhead declaration -->
	<xsd:element name="WarheadData">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLWarheadData"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element name="Warhead" type="Warhead"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<!-- Warhead type -->
	<xsd:complexType name="Warhead">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLWarhead"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="common:ExtendableObject">
				<xsd:sequence>
					<xsd:element name="Effectiveness" type="Effectiveness" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="ImpactAnimation" type="ImpactAnimation" minOccurs="0"/>
				</xsd:sequence>
				<xsd:attribute name="InfDeathAnim" type="InfDeathAnims"/>
				<xsd:attribute name="Spread" type="common:nonNegativeInt"/>
				<xsd:attribute name="Destroys">
					<xsd:simpleType>
						<xsd:list itemType="xsd:string"/>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- Infantry death types (animations) -->
	<xsd:simpleType name="InfDeathAnims">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:typesafeEnumClass name="XMLInfDeathAnims"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="INSTANT"/>
			<xsd:enumeration value="TWIRL"/>
			<xsd:enumeration value="EXPLODE"/>
			<xsd:enumeration value="FLY"/>
			<xsd:enumeration value="BURN"/>
			<xsd:enumeration value="ELECTRO"/>
		</xsd:restriction>
	</xsd:simpleType>

	<!-- Effectiveness against armour types -->
	<xsd:complexType name="Effectiveness">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLEffectiveness"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:attribute name="Armour" type="xsd:string"/>
		<xsd:attribute name="Damage">
			<xsd:simpleType>
				<xsd:restriction base="xsd:float">
					<xsd:minInclusive value="0.0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<!-- Impact animation range and type -->
	<xsd:complexType name="ImpactAnimation">
		<xsd:annotation>
			<xsd:appinfo>
				<jxb:class name="XMLImpactAnimation"/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="media:Animation">
				<xsd:attribute name="Threshold" type="common:nonNegativeInt"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

</xsd:schema>

=== ultraq/redhorizon/old/configs/_Red Alert/XML/Weapons/Warheads.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- ===================================== -->
<!-- Red Horizon XML - Red Alert: Warheads -->
<!-- ===================================== -->

<warhead:WarheadData xmlns="http://www.westwood.com/redalert"
	xmlns:warhead="http://www.ultraq.net.nz/redhorizon/warheads"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ultraq.net.nz/redhorizon/warheads ../../../Schema/Warheads.xsd">

	<!-- Small Arms (machine guns) -->
	<warhead:Warhead
		ID="SA"
		Template="DefaultWarhead"
		InfDeathAnim="TWIRL"
		Spread="3">
		<warhead:Effectiveness
			Armour="none"
			Damage="1.0"/>
		<warhead:Effectiveness
			Armour="wood"
			Damage="0.5"/>
		<warhead:Effectiveness
			Armour="light"
			Damage="0.6"/>
		<warhead:Effectiveness
			Armour="heavy"
			Damage="0.25"/>
		<warhead:Effectiveness
			Armour="concrete"
			Damage="0.25"/>
		<warhead:ImpactAnimation
			ID="SmallArmsImpactAnim"
			Filename="piffpiff.shp"/>
	</warhead:Warhead>

	<!-- Warhead template/defaults -->
	<warhead:Warhead
		ID="DefaultWarhead"
		InfDeathAnim="INSTANT"
		Spread="0">
		<warhead:Effectiveness
			Armour="none"
			Damage="1.0"/>
		<warhead:Effectiveness
			Armour="wood"
			Damage="1.0"/>
		<warhead:Effectiveness
			Armour="light"
			Damage="1.0"/>
		<warhead:Effectiveness
			Armour="heavy"
			Damage="1.0"/>
		<warhead:Effectiveness
			Armour="concrete"
			Damage="1.0"/>
	</warhead:Warhead>

</warhead:WarheadData>
